language: node_js
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
  - yarn clean
  - yarn build:pp

deploy:
  provider: pages
  local-dir: public
  fqdn: urbanli.ch
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master